/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ORG_W3C_DOM_INCLUDED
#define ORG_W3C_DOM_INCLUDED

// Undefined Automake's predefined names
#undef PACKAGE
#undef VERSION

#include <org/w3c/dom/Attr.h>
#include <org/w3c/dom/CaretPosition.h>
#include <org/w3c/dom/CDATASection.h>
#include <org/w3c/dom/CharacterData.h>
#include <org/w3c/dom/Comment.h>
#include <org/w3c/dom/DocumentFragment.h>
#include <org/w3c/dom/Document.h>
#include <org/w3c/dom/DocumentType.h>
#include <org/w3c/dom/DOMConfiguration.h>
#include <org/w3c/dom/DOMError.h>
#include <org/w3c/dom/DOMErrorHandler.h>
#include <org/w3c/dom/DOMException.h>
#include <org/w3c/dom/DOMImplementation.h>
#include <org/w3c/dom/DOMImplementationList.h>
#include <org/w3c/dom/DOMImplementationSource.h>
#include <org/w3c/dom/DOMLocator.h>
#include <org/w3c/dom/DOMStringList.h>
#include <org/w3c/dom/Element.h>
#include <org/w3c/dom/Entity.h>
#include <org/w3c/dom/EntityReference.h>
#include <org/w3c/dom/NamedNodeMap.h>
#include <org/w3c/dom/NameList.h>
#include <org/w3c/dom/Node.h>
#include <org/w3c/dom/NodeList.h>
#include <org/w3c/dom/Notation.h>
#include <org/w3c/dom/ObjectArray.h>
#include <org/w3c/dom/ProcessingInstruction.h>
#include <org/w3c/dom/Text.h>
#include <org/w3c/dom/TypeInfo.h>
#include <org/w3c/dom/UserDataHandler.h>
#include <org/w3c/dom/XMLHttpRequestEventTarget.h>
#include <org/w3c/dom/XMLHttpRequest.h>
#include <org/w3c/dom/XMLHttpRequestUpload.h>
#include <org/w3c/dom/css/Counter.h>
#include <org/w3c/dom/css/CSS2Properties.h>
#include <org/w3c/dom/css/CSSCharsetRule.h>
#include <org/w3c/dom/css/CSSFontFaceRule.h>
#include <org/w3c/dom/css/CSSImportRule.h>
#include <org/w3c/dom/css/CSSMediaRule.h>
#include <org/w3c/dom/css/CSSPageRule.h>
#include <org/w3c/dom/css/CSSPrimitiveValue.h>
#include <org/w3c/dom/css/CSSRule.h>
#include <org/w3c/dom/css/CSSRuleList.h>
#include <org/w3c/dom/css/CSSStyleDeclaration.h>
#include <org/w3c/dom/css/CSSStyleRule.h>
#include <org/w3c/dom/css/CSSStyleSheet.h>
#include <org/w3c/dom/css/CSSUnknownRule.h>
#include <org/w3c/dom/css/CSSValue.h>
#include <org/w3c/dom/css/CSSValueList.h>
#include <org/w3c/dom/css/DocumentCSS.h>
#include <org/w3c/dom/css/DOMImplementationCSS.h>
#include <org/w3c/dom/css/ElementCSSInlineStyle.h>
#include <org/w3c/dom/css/Rect.h>
#include <org/w3c/dom/css/RGBColor.h>
#include <org/w3c/dom/css/ViewCSS.h>
#include <org/w3c/dom/events/DocumentEvent.h>
#include <org/w3c/dom/events/EventException.h>
#include <org/w3c/dom/events/Event.h>
#include <org/w3c/dom/events/EventListener.h>
#include <org/w3c/dom/events/EventTarget.h>
#include <org/w3c/dom/events/MouseEvent.h>
#include <org/w3c/dom/events/MutationEvent.h>
#include <org/w3c/dom/eventsource/EventSource.h>
#include <org/w3c/dom/events/UIEvent.h>
#include <org/w3c/dom/file/Blob.h>
#include <org/w3c/dom/file/FileError.h>
#include <org/w3c/dom/file/FileException.h>
#include <org/w3c/dom/file/File.h>
#include <org/w3c/dom/file/FileReader.h>
#include <org/w3c/dom/file/FileReaderSync.h>
#include <org/w3c/dom/html/ApplicationCache.h>
#include <org/w3c/dom/html/BarProp.h>
#include <org/w3c/dom/html/BeforeUnloadEvent.h>
#include <org/w3c/dom/html/CanvasGradient.h>
#include <org/w3c/dom/html/CanvasPattern.h>
#include <org/w3c/dom/html/CanvasPixelArray.h>
#include <org/w3c/dom/html/CanvasRenderingContext2D.h>
#include <org/w3c/dom/html/DataTransfer.h>
#include <org/w3c/dom/html/DOMSettableTokenList.h>
#include <org/w3c/dom/html/DOMStringMap.h>
#include <org/w3c/dom/html/DOMTokenList.h>
#include <org/w3c/dom/html/DragEvent.h>
#include <org/w3c/dom/html/Function.h>
#include <org/w3c/dom/html/History.h>
#include <org/w3c/dom/html/HTMLAllCollection.h>
#include <org/w3c/dom/html/HTMLAnchorElement.h>
#include <org/w3c/dom/html/HTMLAppletElement.h>
#include <org/w3c/dom/html/HTMLAreaElement.h>
#include <org/w3c/dom/html/HTMLAudioElement.h>
#include <org/w3c/dom/html/HTMLBaseElement.h>
#include <org/w3c/dom/html/HTMLBaseFontElement.h>
#include <org/w3c/dom/html/HTMLBodyElement.h>
#include <org/w3c/dom/html/HTMLBRElement.h>
#include <org/w3c/dom/html/HTMLButtonElement.h>
#include <org/w3c/dom/html/HTMLCanvasElement.h>
#include <org/w3c/dom/html/HTMLCollection.h>
#include <org/w3c/dom/html/HTMLCommandElement.h>
#include <org/w3c/dom/html/HTMLDataListElement.h>
#include <org/w3c/dom/html/HTMLDetailsElement.h>
#include <org/w3c/dom/html/HTMLDirectoryElement.h>
#include <org/w3c/dom/html/HTMLDivElement.h>
#include <org/w3c/dom/html/HTMLDListElement.h>
#include <org/w3c/dom/html/HTMLDocument.h>
#include <org/w3c/dom/html/HTMLElement.h>
#include <org/w3c/dom/html/HTMLEmbedElement.h>
#include <org/w3c/dom/html/HTMLFieldSetElement.h>
#include <org/w3c/dom/html/HTMLFontElement.h>
#include <org/w3c/dom/html/HTMLFormControlsCollection.h>
#include <org/w3c/dom/html/HTMLFormElement.h>
#include <org/w3c/dom/html/HTMLFrameElement.h>
#include <org/w3c/dom/html/HTMLFrameSetElement.h>
#include <org/w3c/dom/html/HTMLHeadElement.h>
#include <org/w3c/dom/html/HTMLHeadingElement.h>
#include <org/w3c/dom/html/HTMLHRElement.h>
#include <org/w3c/dom/html/HTMLHtmlElement.h>
#include <org/w3c/dom/html/HTMLIFrameElement.h>
#include <org/w3c/dom/html/HTMLImageElement.h>
#include <org/w3c/dom/html/HTMLInputElement.h>
#include <org/w3c/dom/html/HTMLKeygenElement.h>
#include <org/w3c/dom/html/HTMLLabelElement.h>
#include <org/w3c/dom/html/HTMLLegendElement.h>
#include <org/w3c/dom/html/HTMLLIElement.h>
#include <org/w3c/dom/html/HTMLLinkElement.h>
#include <org/w3c/dom/html/HTMLMapElement.h>
#include <org/w3c/dom/html/HTMLMarqueeElement.h>
#include <org/w3c/dom/html/HTMLMediaElement.h>
#include <org/w3c/dom/html/HTMLMenuElement.h>
#include <org/w3c/dom/html/HTMLMetaElement.h>
#include <org/w3c/dom/html/HTMLMeterElement.h>
#include <org/w3c/dom/html/HTMLModElement.h>
#include <org/w3c/dom/html/HTMLObjectElement.h>
#include <org/w3c/dom/html/HTMLOListElement.h>
#include <org/w3c/dom/html/HTMLOptGroupElement.h>
#include <org/w3c/dom/html/HTMLOptionElement.h>
#include <org/w3c/dom/html/HTMLOptionsCollection.h>
#include <org/w3c/dom/html/HTMLOutputElement.h>
#include <org/w3c/dom/html/HTMLParagraphElement.h>
#include <org/w3c/dom/html/HTMLParamElement.h>
#include <org/w3c/dom/html/HTMLPreElement.h>
#include <org/w3c/dom/html/HTMLProgressElement.h>
#include <org/w3c/dom/html/HTMLPropertiesCollection.h>
#include <org/w3c/dom/html/HTMLQuoteElement.h>
#include <org/w3c/dom/html/HTMLScriptElement.h>
#include <org/w3c/dom/html/HTMLSelectElement.h>
#include <org/w3c/dom/html/HTMLSourceElement.h>
#include <org/w3c/dom/html/HTMLSpanElement.h>
#include <org/w3c/dom/html/HTMLStyleElement.h>
#include <org/w3c/dom/html/HTMLTableCaptionElement.h>
#include <org/w3c/dom/html/HTMLTableCellElement.h>
#include <org/w3c/dom/html/HTMLTableColElement.h>
#include <org/w3c/dom/html/HTMLTableDataCellElement.h>
#include <org/w3c/dom/html/HTMLTableElement.h>
#include <org/w3c/dom/html/HTMLTableHeaderCellElement.h>
#include <org/w3c/dom/html/HTMLTableRowElement.h>
#include <org/w3c/dom/html/HTMLTableSectionElement.h>
#include <org/w3c/dom/html/HTMLTextAreaElement.h>
#include <org/w3c/dom/html/HTMLTimeElement.h>
#include <org/w3c/dom/html/HTMLTitleElement.h>
#include <org/w3c/dom/html/HTMLUListElement.h>
#include <org/w3c/dom/html/HTMLUnknownElement.h>
#include <org/w3c/dom/html/HTMLVideoElement.h>
#include <org/w3c/dom/html/ImageData.h>
#include <org/w3c/dom/html/Location.h>
#include <org/w3c/dom/html/MediaError.h>
#include <org/w3c/dom/html/MessageChannel.h>
#include <org/w3c/dom/html/MessageEvent.h>
#include <org/w3c/dom/html/MessagePort.h>
#include <org/w3c/dom/html/Navigator.h>
#include <org/w3c/dom/html/PopStateEvent.h>
#include <org/w3c/dom/html/PropertyNodeList.h>
#include <org/w3c/dom/html/RadioNodeList.h>
#include <org/w3c/dom/html/Screen.h>
#include <org/w3c/dom/html/Selection.h>
#include <org/w3c/dom/html/StyleMedia.h>
#include <org/w3c/dom/html/TextMetrics.h>
#include <org/w3c/dom/html/TimeRanges.h>
#include <org/w3c/dom/html/UndoManagerEvent.h>
#include <org/w3c/dom/html/UndoManager.h>
#include <org/w3c/dom/html/ValidityState.h>
#include <org/w3c/dom/html/Window.h>
#include <org/w3c/dom/ls/DOMImplementationLS.h>
#include <org/w3c/dom/ls/LSException.h>
#include <org/w3c/dom/ls/LSInput.h>
#include <org/w3c/dom/ls/LSLoadEvent.h>
#include <org/w3c/dom/ls/LSOutput.h>
#include <org/w3c/dom/ls/LSParserFilter.h>
#include <org/w3c/dom/ls/LSParser.h>
#include <org/w3c/dom/ls/LSProgressEvent.h>
#include <org/w3c/dom/ls/LSResourceResolver.h>
#include <org/w3c/dom/ls/LSSerializerFilter.h>
#include <org/w3c/dom/ls/LSSerializer.h>
#include <org/w3c/dom/ranges/DocumentRange.h>
#include <org/w3c/dom/ranges/RangeException.h>
#include <org/w3c/dom/ranges/Range.h>
#include <org/w3c/dom/stylesheets/DocumentStyle.h>
#include <org/w3c/dom/stylesheets/LinkStyle.h>
#include <org/w3c/dom/stylesheets/MediaList.h>
#include <org/w3c/dom/stylesheets/StyleSheet.h>
#include <org/w3c/dom/stylesheets/StyleSheetList.h>
#include <org/w3c/dom/traversal/DocumentTraversal.h>
#include <org/w3c/dom/traversal/NodeFilter.h>
#include <org/w3c/dom/traversal/NodeIterator.h>
#include <org/w3c/dom/traversal/TreeWalker.h>
#include <org/w3c/dom/validation/CharacterDataEditVAL.h>
#include <org/w3c/dom/validation/DocumentEditVAL.h>
#include <org/w3c/dom/validation/ElementEditVAL.h>
#include <org/w3c/dom/validation/ExceptionVAL.h>
#include <org/w3c/dom/validation/NodeEditVAL.h>
#include <org/w3c/dom/views/AbstractView.h>
#include <org/w3c/dom/views/ClientRect.h>
#include <org/w3c/dom/views/ClientRectList.h>
#include <org/w3c/dom/views/DocumentView.h>
#include <org/w3c/dom/webdatabase/DatabaseCallback.h>
#include <org/w3c/dom/webdatabase/Database.h>
#include <org/w3c/dom/webdatabase/DatabaseSync.h>
#include <org/w3c/dom/webdatabase/SQLError.h>
#include <org/w3c/dom/webdatabase/SQLException.h>
#include <org/w3c/dom/webdatabase/SQLResultSet.h>
#include <org/w3c/dom/webdatabase/SQLResultSetRowList.h>
#include <org/w3c/dom/webdatabase/SQLStatementCallback.h>
#include <org/w3c/dom/webdatabase/SQLStatementErrorCallback.h>
#include <org/w3c/dom/webdatabase/SQLTransactionCallback.h>
#include <org/w3c/dom/webdatabase/SQLTransactionErrorCallback.h>
#include <org/w3c/dom/webdatabase/SQLTransaction.h>
#include <org/w3c/dom/webdatabase/SQLTransactionSyncCallback.h>
#include <org/w3c/dom/webdatabase/SQLTransactionSync.h>
#include <org/w3c/dom/webdatabase/SQLVoidCallback.h>
#include <org/w3c/dom/webgl/WebGLActiveInfo.h>
#include <org/w3c/dom/webgl/WebGLArrayBuffer.h>
#include <org/w3c/dom/webgl/WebGLArray.h>
#include <org/w3c/dom/webgl/WebGLBuffer.h>
#include <org/w3c/dom/webgl/WebGLByteArray.h>
#include <org/w3c/dom/webgl/WebGLContextAttributes.h>
#include <org/w3c/dom/webgl/WebGLFloatArray.h>
#include <org/w3c/dom/webgl/WebGLFramebuffer.h>
#include <org/w3c/dom/webgl/WebGLIntArray.h>
#include <org/w3c/dom/webgl/WebGLObjectArray.h>
#include <org/w3c/dom/webgl/WebGLObject.h>
#include <org/w3c/dom/webgl/WebGLProgram.h>
#include <org/w3c/dom/webgl/WebGLRenderbuffer.h>
#include <org/w3c/dom/webgl/WebGLRenderingContext.h>
#include <org/w3c/dom/webgl/WebGLResourceLostEvent.h>
#include <org/w3c/dom/webgl/WebGLShader.h>
#include <org/w3c/dom/webgl/WebGLShortArray.h>
#include <org/w3c/dom/webgl/WebGLTexture.h>
#include <org/w3c/dom/webgl/WebGLUniformLocation.h>
#include <org/w3c/dom/webgl/WebGLUnsignedByteArray.h>
#include <org/w3c/dom/webgl/WebGLUnsignedIntArray.h>
#include <org/w3c/dom/webgl/WebGLUnsignedShortArray.h>
#include <org/w3c/dom/websocket/WebSocket.h>
#include <org/w3c/dom/webstorage/StorageEvent.h>
#include <org/w3c/dom/webstorage/Storage.h>
#include <org/w3c/dom/workers/AbstractWorker.h>
#include <org/w3c/dom/workers/ErrorEvent.h>
#include <org/w3c/dom/workers/SharedWorker.h>
#include <org/w3c/dom/workers/WorkerGlobalScope.h>
#include <org/w3c/dom/workers/Worker.h>
#include <org/w3c/dom/workers/WorkerLocation.h>
#include <org/w3c/dom/workers/WorkerNavigator.h>
#include <org/w3c/dom/xpath/XPathEvaluator.h>
#include <org/w3c/dom/xpath/XPathException.h>
#include <org/w3c/dom/xpath/XPathExpression.h>
#include <org/w3c/dom/xpath/XPathNamespace.h>
#include <org/w3c/dom/xpath/XPathNSResolver.h>
#include <org/w3c/dom/xpath/XPathResult.h>

#endif  // ORG_W3C_DOM_INCLUDED
