// Test [Null], [Undefined]
interface X {
  [Null=Null] attribute string x;
  [Null=Empty] attribute string y;
  [Undefined=Null] attribute string u;
  [Undefined=Empty] attribute string v;
  void a([Null=Null] in string s);
  void b([Null=Empty] in string s);
  void c([Undefined=Null] in string s);
  void d([Undefined=Empty] in string s);
};
