interface I
{
    long op();
    #pragma ID I = "DCE:B196B286-BAB4-101A-B69C-00AA00241D07";
};

interface J : I
{
    long op();
    #pragma ID J = "DCE:8e76c0d0-5f02-4566-9bb5-bb11e677a889";
};
