module A
{
    typedef long B[2][2];

    exception E
    {
        long code;
    };

    struct X
    {
        B s[4];
        B t;
        sequence<long> u;
    };

    struct Y
    {
        long u;
        sequence<X> v;
    };

    interface Z
    {
        void op(in Y y) raises(E);
    };
};
