module A
{
    exception E
    {
        long code;
    };

    typedef long D[4];
};

module A
{
    interface I
    {
        void op7(in any a) raises(E);
        any op9() raises(E);

        void op10(in D d);
        D op12();

        void op13(in I i);
        I op15();

        attribute string name;
        attribute any option;
        attribute D misc;
        attribute I parent;
    };
};
