module A
{
    interface I
    {
        [IndexGetter] float getByIndex(in unsigned long index);
        [IndexSetter] void setByIndex(in unsigned long index, in float value);
        [NameGetter] float get(in string name);
        [NameSetter] void set(in string name, in float value);
    };
};
