#include "Interface.idl"

module dom
{
    typedef unsigned long long DOMTimeStamp;

    interface Node : Interface
    {
        readonly attribute string nodeName;
    };

    interface Element : Node
    {
      readonly attribute string tagName;
    };

    interface Document : Node
    {
        Element getElementById(in string elementId);
    };
};
