#include "dom.idl"

module html
{
    typedef dom::Node Node;
    typedef dom::Document Document;
    typedef dom::Element Element;

    interface HTMLElement : Element
    {
        attribute string id;
    };

    interface HTMLCanvasElement : HTMLElement
    {
        attribute unsigned long width;
        attribute unsigned long height;
        Object getContext(in string contextId);
    };

    interface CanvasRenderingContext2D : Interface
    {
        attribute any fillStyle;
        void fillRect(in float x, in float y, in float width, in float height);
    };
};
