// File: views.idl

#ifndef _VIEWS_IDL_
#define _VIEWS_IDL_

#include "dom.idl"

module views
{
  interface DocumentView;

  interface AbstractView : Interface {
    readonly attribute DocumentView     document;
  };

  [ImplementedOn=dom::Document]
  interface DocumentView : Interface {
    readonly attribute AbstractView     defaultView;
  };
};

#endif // _VIEWS_IDL_
